# Guild join link
[[redirects]]
  from = "/join"
  to = "https://www.guildofstudents.com/studentgroups/societies/css/"

[[redirects]]
  from = "/guild"
  to = "/join"


# EPS Link
[[redirects]]
  from = "/eps"
  to = "https://www.birmingham.ac.uk/university/colleges/eps/eps-community/students/societies/css.aspx"


# Sponsorship Proposal
[[redirects]]
  from = "/sponsor"
  to = "/assets/sponsorship/CSS_Sponsorship_Proposal.pdf"


# Society Constitution
[[redirects]]
  from = "/constitution"
  to = "/assets/constitution.pdf"


# Socials
[[redirects]]
  from = "/facebook"
  to = "https://facebook.com/groups/CSSUoB"

[[redirects]]
  from = "/fb"
  to = "/facebook"

[[redirects]]
  from = "/instagram"
  to = "https://instagram.com/cssbham"

[[redirects]]
  from = "/ig"
  to = "/instagram"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/cssbham"

[[redirects]]
  from = "/tw"
  to = "/twitter"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/company/cssbham/"

[[redirects]]
  from = "/in"
  to = "/linkedin"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/uftEqwy"

[[redirects]]
  from = "/di"
  to = "/discord"

[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UC-nWGWJv8wi3nw4YG55Vd0A"

[[redirects]]
  from = "/yt"
  to = "/youtube"

[[redirects]]
  from = "/email"
  to = "mailto:css@guild.bham.ac.uk"

[[redirects]]
  from = "/github"
  to = "https://github.com/CSSUoB/cssuob.github.io"

[[redirects]]
  from = "/gh"
  to = "/github"

[[redirects]]
  from = "/texbot"
  to = "https://github.com/CSSUoB/TeX-Bot-Py-V2"

[[redirects]]
  from = "/tex"
  to = "/texbot"


# Ball
[[redirects]]
  from = "/ball"
  to = "/ball/2023"

[[redirects]]
  from = "/ball/2023/photos"
  to = "https://photos.app.goo.gl/PZEahyV3CJed7ttA6"

[[redirects]]
  from = "/ball/2022/photos"
  to = "https://photos.app.goo.gl/bSyPR6fyHGtGDW6h9"

[[redirects]]
  from = "/ball/2020/photos"
  to = "https://www.facebook.com/media/set/?set=oa.2609144112656487"


# Calendar
[[redirects]]
  from = "/calender"
  to = "/calendar"

[[redirects]]
  from = "/cal"
  to = "/calendar"

[[redirects]]
  from = "/soon"
  to = "/calendar"


# AGMs
[[redirects]]
  from = "/agm/2022/agenda"
  to = "/assets/agendas/2022/agenda_22_05_04.pdf"

[[redirects]]
  from = "/agm/2023/agenda"
  to = "/assets/agendas/agenda_23_05_10_AGM.pdf"


# Feedback
[[redirects]]
  from = "/feedback"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSe1jAEFmNEc4YQmXtvDMhFZGFzk1xLIJ3WV5q2FxVtYh7fnUw/viewform?usp=sf_link"


# Pizza Typo
[[redirects]]
  from = "/pizzas"
  to = "/pizza"


# Hoodies -- PLACEHOLDER, NOT ON SALE
[[redirects]]
  from = "/hoodies"
  to = "/404"

[[redirects]]
  from = "/hoodie"
  to = "/404"


# Ducks
[[redirects]]
  from = "/ducks"
  to = "https://guildofstudents.com/events/6531/7063"

[[redirects]]
  from = "/duck"
  to = "/ducks"

[[redirects]]
  from = "/quack"
  to = "/ducks"

[[redirects]]
  from = "/quak"
  to = "/ducks"


# Scavenger Hunt 18-09-2023 -> 25-09-2023
[[redirects]]
  from = "/hunt"
  to = "https://forms.gle/AfeZwccHvwt2Qnpo6"

[[redirects]]
  from = "/scavenger-hunt"
  to = "/hunt"


# Board Games Night 18-09-2023
[[redirects]]
  from = "/bringing-games"
  to = "https://docs.google.com/spreadsheets/d/1W21xL9TJCRPXEcq4MfV6-jMBSYXK2fRuOnX3JJQSVyM/"

[[redirects]]
  from = "/board-games-night"
  to = "https://forms.gle/etTB5YRzgH7nUMPJ7"

[[redirects]]
  from = "/bgn"
  to = "/board-games-night"

[[redirects]]
  from = "/bgn-walking-train"
  to = "https://www.google.com/maps/place/52%C2%B027'31.7%22N+1%C2%B055'34.1%22W/@52.4586142,-1.9261034,18.26z/data=!4m4!3m3!8m2!3d52.458793!4d-1.92614?entry=ttu"

[[redirects]] # emergency "whoops I typed the link into the QR code generator for the quiet room signage wrong" redirect
  from = "/commitee"
  to = "/committee"

# Ming Moon 20-09-2023
[[redirects]]
  from = "/ming-moon"
  to = "https://www.eventbrite.co.uk/e/css-goes-to-ming-moon-tickets-712969449817?aff=oddtdtcreator"


# EGM 2023-11-01
[[redirects]]
  from = "/vote"
  to = "https://vote.cssbham.com"

[[redirects]]
  from = "/egm"
  to = "https://vote.cssbham.com"

[[redirects]]
  from = "/agm"
  to = "https://vote.cssbham.com"

# Pub crawl 2023-11-24
[[redirects]]
  from = "/pubcrawl"
  to = "https://www.guildofstudents.com/events/6531/8295/"

[[redirects]]
  from = "/pub"
  to = "/pubcrawl"

# Roller Skating 2023-11-16
[[redirects]]
  from = "/rollerskating"
  to = "https://www.skiddle.com/whats-on/Birmingham/Roller-Jam/Get-Down---Free-Entry-and-241-Cocktails-6pm-2am-For-Ages-18/36707712/"

[[redirects]]
  from = "/skate"
  to = "https://www.skiddle.com/whats-on/Birmingham/Roller-Jam/Get-Down---Free-Entry-and-241-Cocktails-6pm-2am-For-Ages-18/36707712/"
